export const REQUEST_RETAILERS_SEARCH = 'REQUEST_RETAILERS_SEARCH';
export const RECEIVE_RETAILERS_SEARCH = 'RECEIVE_RETAILERS_SEARCH';
export const CLEAR_RETAILER_SEARCH = 'CLEAR_RETAILER_SEARCH';

export const REQUEST_RETAILER_DEM_LIST = 'REQUEST_RETAILER_DEM_LIST';
export const RECEIVE_RETAILER_DEM_LIST = 'RECEIVE_RETAILER_DEM_LIST';

export const REQUEST_RETAILER = 'REQUEST_RETAILER';
export const RECEIVE_RETAILER = 'RECEIVE_RETAILER';

export const REQUEST_RETAILERS = 'REQUEST_RETAILERS';
export const RECEIVE_RETAILERS = 'RECEIVE_RETAILERS';

export const REQUEST_ROOT_PRODUCTS = 'REQUEST_ROOT_PRODUCTS';
export const RECEIVE_ROOT_PRODUCTS = 'RECEIVE_ROOT_PRODUCTS';

export const REQUEST_ACTIVITIES = 'REQUEST_ACTIVITIES';
export const RECEIVE_ACTIVITIES = 'RECEIVE_ACTIVITIES';

export const REQUEST_SEARCH_ROOT_PRODUCTS = 'REQUEST_SEARCH_ROOT_PRODUCTS';
export const RECEIVE_SEARCH_ROOT_PRODUCTS = 'RECEIVE_SEARCH_ROOT_PRODUCTS';
export const CLEAR_SEARCH_ROOT_PRODUCTS = 'CLEAR_SEARCH_ROOT_PRODUCTS';
export const SHOW_ROOT_PRODUCT_SEARCH = 'SHOW_ROOT_PRODUCT_SEARCH';
export const HIDE_ROOT_PRODUCT_SEARCH = 'HIDE_ROOT_PRODUCT_SEARCH';
export const SET_ROOT_PRODUCT_SEARCH_TERM = 'SET_ROOT_PRODUCT_SEARCH_TERM';
export const TOGGLE_INCLUDE_PHASED_OUT = 'TOGGLE_INCLUDE_PHASED_OUT';

export const REQUEST_SET_ROOT_PRODUCT = 'REQUEST_SET_ROOT_PRODUCT';
export const RECEIVE_SET_ROOT_PRODUCT = 'RECEIVE_SET_ROOT_PRODUCT';

export const REQUEST_UPDATE_DEM_LIST_DETAILS = 'REQUEST_UPDATE_DEM_LIST_DETAILS';
export const RECEIVE_UPDATE_DEM_LIST_DETAILS = 'RECEIVE_UPDATE_DEM_LIST_DETAILS';

export const REQUEST_EMPLOYEE_NAME = 'REQUEST_EMPLOYEE_NAME';
export const RECEIVE_EMPLOYEE_NAME = 'RECEIVE_EMPLOYEE_NAME';

export const FETCH_ERROR = 'FETCH_ERROR';

export const REQUEST_RETAILER_DEM_LISTS = 'REQUEST_RETAILER_DEM_LISTS';
export const RECEIVE_RETAILER_DEM_LISTS = 'RECEIVE_RETAILER_DEM_LISTS';