export const REQUEST_RETAILERS = 'REQUEST_RETAILERS';
export const RECEIVE_RETAILERS = 'RECEIVE_RETAILERS';
export const CLEAR_RETAILER_SEARCH = 'CLEAR_RETAILER_SEARCH';

export const REQUEST_RETAILER_DEM_LIST = 'REQUEST_RETAILER_DEM_LIST';
export const RECEIVE_RETAILER_DEM_LIST = 'RECEIVE_RETAILER_DEM_LIST';

export const REQUEST_RETAILER = 'REQUEST_RETAILER';
export const RECEIVE_RETAILER = 'RECEIVE_RETAILER';

export const REQUEST_ROOT_PRODUCTS = 'REQUEST_ROOT_PRODUCTS';
export const RECEIVE_ROOT_PRODUCTS = 'RECEIVE_ROOT_PRODUCTS';

export const REQUEST_SEARCH_ROOT_PRODUCTS = 'REQUEST_SEARCH_ROOT_PRODUCTS';
export const RECEIVE_SEARCH_ROOT_PRODUCTS = 'RECEIVE_SEARCH_ROOT_PRODUCTS';
export const CLEAR_SEARCH_ROOT_PRODUCTS = 'CLEAR_SEARCH_ROOT_PRODUCTS';
export const SHOW_ROOT_PRODUCT_SEARCH = 'SHOW_ROOT_PRODUCT_SEARCH';
export const HIDE_ROOT_PRODUCT_SEARCH = 'HIDE_ROOT_PRODUCT_SEARCH';
export const SET_ROOT_PRODUCT_SEARCH_TERM = 'SET_ROOT_PRODUCT_SEARCH_TERM';

export const REQUEST_SET_ROOT_PRODUCT = 'REQUEST_SET_ROOT_PRODUCT';
export const RECEIVE_SET_ROOT_PRODUCT = 'RECEIVE_SET_ROOT_PRODUCT';