export const REQUEST_RETAILERS = 'REQUEST_RETAILERS';
export const RECEIVE_RETAILERS = 'RECEIVE_RETAILERS';
export const CLEAR_RETAILER_SEARCH = 'CLEAR_RETAILER_SEARCH';

export const REQUEST_RETAILER_DEM_LIST = 'REQUEST_RETAILER_DEM_LIST';
export const RECEIVE_RETAILER_DEM_LIST = 'RECEIVE_RETAILER_DEM_LIST';